### ISSUE TITLE
feat: Custom Plugin 개발 표준 수립

### ISSUE THREAD

**Issue by dev-shin** [shinhancard/dev-portal#26]
### Description

플러그인 생성 및 구현 방안 표준 수립
샘플코드 작성

**Comment by dev-shin** [comment]
Create Custom Plugin

 -> yarn new --select plugin
 -> Enter the ID of the plugin
/Plugins/{pluginId} 경로로 Route 설정까지 완료된 Custom Plugin이 생성 된다.

![Image](https://github.com/hellices/dev-portal/assets/57754997/d5fa17a2-e506-431b-bde5-3355c44bb61d)

생성된 Custom Plugin 확인
 -> http://localhost:3000/{pluginId}

![Image](https://github.com/hellices/dev-portal/assets/57754997/0de17b15-10aa-489f-a0ee-0e71edb50789)

**Comment by dev-shin** [comment]
Plugin Menu 등록

src/componenets/Root/Root.tsx

Icon import
`import CreditCardIcon from '@material-ui/icons/CreditCard';`
Material UI ICON 의 경우 아래 페이지에서 검색 가능 
https://v4.mui.com/components/material-icons/

Sidebar Item 추가
`<SidebarItem icon={CreditCardIcon} to="shc-custom-plugin-sample" text="SamplePlugin" />`

<img width="873" alt="스크린샷 2023-07-12 오후 3 53 26" src="https://github.com/hellices/dev-portal/assets/57754997/220707b0-4145-4e17-becc-d4c157675119">

**Comment by hellices** [comment]
Import 순서가 변경됨
자동완성기능 공통 설정으로 배포 필요

**Comment by dev-shin** [comment]
[CODE_STYLE.md](https://github.com/hellices/dev-portal/blob/feature/custom-plugin-sample/CODE_STYLE.md)

**Comment by YOOMYE89** [comment]
구조 완료 작업 관련 플로우 작성하여 공유 예정
7/17
