### ISSUE TITLE
feat: AWS EKS 대상 CI / CD 추가 

### ISSUE THREAD

**Issue by seowjin1060** [shinhancard/dev-portal#30]
### Description

[기능]
현재 backstage 환경을 AWS EKS에 배포할 파이프라인 작성

[필요한 이유]
향후 패치 적용된 버전을 주기적으로 반영 / 테스트

[주의사항]
공개 repo이므로 AWS 계정 노출 안되게 해야함 (variables로 지정?)

**Comment by hellices** [comment]
kuberentes deploy guide - https://backstage.io/docs/deployment/k8s

**Comment by hellices** [comment]
3rd try

2nd try의 로그를 보면 base image의 node version이 16이어서 오류가 나는 것으로 확인
![스크린샷 2023-07-12 오후 2 07 29](https://github.com/hellices/dev-portal/assets/5661904/09de5d26-96c3-47bf-b080-985f8f630294)

backend dockerfile의 base image를 18로 변경 후 테스트
success!
![스크린샷 2023-07-12 오후 2 41 06](https://github.com/hellices/dev-portal/assets/5661904/1be0e4a6-e69a-46af-8f70-2dde666ff669)


image run 결과 정상 동작 확인
docker run -it -p 7007:7007 backstage 
![스크린샷 2023-07-12 오후 2 41 35](https://github.com/hellices/dev-portal/assets/5661904/4d895531-8029-4c97-9d44-adbfcf9cafd7)

**Comment by hellices** [comment]
배포를 해보자

---
1. github actions에서 workflow 생성 : https://docs.github.com/ko/actions/using-workflows/about-workflows
2. oidc를 이용한 인증 처리 : https://docs.github.com/ko/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
3. build workflow : https://docs.github.com/ko/actions/automating-builds-and-tests/building-and-testing-nodejs
4. github actions에서 aws 에 배포 : https://docs.github.com/ko/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

**Comment by hellices** [comment]
workflow 
- test ? 
- build image
- push to ecr
- deploy to eks

build image는 PR과 main branch 병합되는 경우
push, deploy는 main branch 병합되는 경우

**Comment by seowjin1060** [comment]
AWS의 계정에서 생성된 OIDC 엔드포인트에 신뢰 엔드포인트로 아래 사항 추가 필요 
```
"Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:hellices/dev-portal:*"
                },
```

위 설정을 추가하면 AWS측에서 본 repo의  요청을 받을시 임시 키를 토큰화하여 응답하게됨 

해당 키는 workflow에 노출되지 않으며, 실행중에만 유효

**Comment by hellices** [comment]
secret 등록 - AWS_ROLE_ARN

**Comment by seowjin1060** [comment]
Main 브랜치에 작업해야 동작하여 Fork한 repo에서 작업중
https://github.com/seowjin1060/dev-portal/actions

**Comment by seowjin1060** [comment]
Yarn build시 Buildkit을 활성화하는 것을 요구함 (멀티 플랫폼 빌드)
![image](https://github.com/hellices/dev-portal/assets/26168539/4b89603d-313f-4406-9e6c-307896704a4e)
커맨드와 마찬가지로 DOCKER_BUILDKIT=1을 붙이거나 env로 정의해서 해결 가능
(로컬 환경은 docker.json에 환경 변수 등록 가능)

**Comment by seowjin1060** [comment]
ECR 업로드까지 완료,

현재는 프로젝트 전체를 yarn 빌드하여 생긴 Docker를 업로드 하는 형태

프로젝트 initialize #7 가 완료되면 monorepo 형태를 띄므로,
`   paths:
      - 'service_A/**'`
로 현재 스크립트에 서비스별 분기 추가

**Comment by seowjin1060** [comment]
EKS 배포는 Helm 차트 형식으로 적용 예정이며, 프로젝트별 템플릿 작성예정

**Comment by seowjin1060** [comment]
클러스터 작업시 tcp timeout 발생

AWS EKS 클러스터 방화벽 대상 github action 접근 허용 필요
![image](https://github.com/hellices/dev-portal/assets/26168539/312c9b5a-59da-4eab-8ef1-6cc86057d476)

**Comment by seowjin1060** [comment]
> 클러스터 작업시 서비스 주소로 tcp timeout 발생
> 
> AWS EKS의 swa 클러스터 방화벽 대상 github action 접근 허용 필요 ![image](https://user-images.githubusercontent.com/26168539/254147635-312c9b5a-59da-4eab-8ef1-6cc86057d476.png)

Flux 기반으로 EKS측에서 github을 당겨가도록 시도

**Comment by seowjin1060** [comment]
FLUX 혹은 github action을 eks에 배포 필요 
- github action을 배포할 경우 어짜피 github에서 runner에 접근 불가 (public access)
- flux 배포후 당겨가도록 시도

**Comment by seowjin1060** [comment]
minikube에서 배포 테스트 완료했고 SWA EKS에 flux 배포해서 적용중

**Comment by hellices** [comment]
CI구성까지만 여기서 진행하고 CD(flux)는 #66 에서 이어서 진행
빌드 구성 시 태그에 넘버링을 추가해서 버전 관리가 가능하도록 해야 함 @seowjin1060

**Comment by hellices** [comment]
https://fluxcd.io/flux/guides/image-update/#imagepolicy-examples
image policy example
