### ISSUE TITLE
feat: backstage action으로 동적 Gradle, Maven 파일 설정

### ISSUE THREAD

**Issue by jobum97** [shinhancard/dev-portal#58]
### Description
[history](https://github.com/shinhancard/dev-portal/issues/27)
backstage action으로 동적 Gradle, Maven 파일 설정

**Comment by jobum97** [comment]
https://www.youtube.com/playlist?list=PLSI4KG8iLsU4trUYpad8_qPH81pCjaba2

**Comment by jobum97** [comment]
![image](https://github.com/shinhancard/dev-portal/assets/51693368/c44896c8-1a4c-4a48-977a-207a16b6ef13)
action 통해 파일 생성

**Comment by jobum97** [comment]
화면에서 동적으로 데이터 받아

**Comment by jobum97** [comment]
<img width="767" alt="image" src="https://github.com/shinhancard/dev-portal/assets/51693368/63d429bc-3603-4b58-922e-d1aa14ce7663">

<img width="767" alt="image" src="https://github.com/shinhancard/dev-portal/assets/51693368/bf0efbec-3906-4a36-8587-b8976880ad88">
프론트단에선 동적으로 입력 받는 것까지 된 상황 백단에서 이를 제대로 받는 부분에서 에러가 나고 있어 잡는 중

**Comment by jobum97** [comment]
@hemoi 
https://github.com/shinhancard/dev-portal-catalog-template 
접근 권한 요청함. 개발중인 템플릿 옮기려는데 권한이 없어 push가 안되는 문제 발생



![Image](https://github.com/shinhancard/dev-portal/assets/51693368/2d0d755d-1256-47e1-9b5e-6fcb524a0890)

**Comment by jobum97** [comment]
우선 gradle dependency 들을 입력받아 build.gradle 들 중 일부를 파일로 만드는 부분까지 진행

현재 생각은 기본적인 build.gradle은 스켈레톤 코드로 들어가고 필요한 값들은 변수로 넣어주고

dependencies도 backend 쪽에서 가공을 해서 파일로 떨구는 것이 아닌 fetch action을 통해 입력해주는 방식으로 바꾸는 것이 나을 것 같아 이에 대한 내용은 새로운 이슈로 진행하고자 함

**Comment by hellices** [comment]
@jobum97 머지 전에 템플릿 프로젝트 develop -> master로 병합 필요. 이 때 develop 브랜치 삭제하지 말것.

병합되면 app-config.yaml의 url 경로도 바꿔줘야함
