### ISSUE TITLE
feat: Flux 기반 배포 기능 추가

### ISSUE THREAD

**Issue by seowjin1060** [shinhancard/dev-portal#59]
### Description

private cluster에 배포하기 위한 FLUX CD 연동 
![image](https://github.com/shinhancard/dev-portal/assets/26168539/734bbfaa-3f53-4735-9db6-c51536887c50)

**Comment by seowjin1060** [comment]
만약의 예외를 대비하여 fork repo / minikube 대상으로 생성 테스트, 

1. 로컬(mac) 환경에서 flux cli를 통해 minikube에 bootstrap (초기구축 )
![image](https://github.com/shinhancard/dev-portal/assets/26168539/3afb8e50-b1b5-4f2e-8414-7e5c88398337)

2. flux namespace로 현재 kubectl에 등록된 클러스터로 flux 노드가 배포됨 (따라서 bastion에서 실행시 EKS에 배포됨. 주의)
![image](https://github.com/shinhancard/dev-portal/assets/26168539/fd28a029-251b-46ae-a9e9-e00d81ecc173)

3.또한 초기 구축시 설정한 repo명으로 실제 github에 repo가 생성된것을 확인 
![image](https://github.com/shinhancard/dev-portal/assets/26168539/b28f0982-762d-4ba6-96df-f1934e82bf04)

4. 자동생성된 repo에 Kustomization 존재, Helm으로 대체 가능한지 테스트해보겠음 
![image](https://github.com/shinhancard/dev-portal/assets/26168539/7281e6db-2adf-469e-8843-f360ef2fab2b)

**Comment by seowjin1060** [comment]
github helm repo 생성중 https://github.com/seowjin1060/flux-test

완성 후 shinhancard로 transfer 예정

**Comment by seowjin1060** [comment]
[helm 기반 flux 배포 튜토리얼]
https://www.youtube.com/watch?v=UhV8kYcb9Mc&ab_channel=GeertBaeke

[flux <-> github action 연동방안]
https://fluxcd.io/flux/use-cases/gh-actions-helm-promotion/
-> flux repo의 github action을 source repo에서 빌드 후 호출함 
-> flux repo의 github은 Menifest를 업데이트하여 Flux가 배포하도록 유도 
-> 배포 상태와 flux측 작업을 추적 가능한 방법을 구상중

**Comment by hellices** [comment]
8/2(수) 까지 작업해보고 상황 공유 예정.
이번 주까지는 배포를 완료하는것이 목표

**Comment by hellices** [comment]
Duplicate of #66
