### ISSUE TITLE
feat: 권한 관리 기능 추가

### ISSUE THREAD

**Issue by hellices** [shinhancard/dev-portal#62]
### Description

Description
[기능]
시스템의 권한을 설계하고 각 권한 별 사용자를 어떻게 관리할 지

[주의사항]
.

**Comment by seowjin1060** [comment]
backstage 자체에 user 권한을 만들고 관리할 수 있는지 알아보겠음. (plugin 포함)

없으면 관리 방안 작성해서 업데이트 예정

**Comment by hellices** [comment]
https://backstage.io/docs/auth/identity-resolver

**Comment by seowjin1060** [comment]
https://backstage.io/docs/auth/
https://backstage.io/docs/auth/add-auth-provider/

github oauth provider를 우선적으로 적용중,

사내 환경으로 전환시 gitlab 계정으로 연동하는 것을 검토 필요 (gitlab or SDMS)

프로젝트 관리가 gitlab으로 전환된다면, SDMS 연동은 필요없을것으로 보임 

만약 CF등을 템플릿으로 관리하려면 SDMS 커스텀 oauth plugin을 개발
https://backstage.io/docs/auth/oauth2-proxy/provider

**Comment by hellices** [comment]
내부에 rhsso(keycloak)이 있어 연계 가능

**Comment by seowjin1060** [comment]
https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app

github 인증 연동을 위해 oauth app 생성 필요

**Comment by hellices** [comment]
생성완료.
secret은 카톡으로 보냄

![Image](https://github.com/shinhancard/dev-portal/assets/5661904/ceadf38e-a365-42d7-b42a-c4c70a949809)
