### ISSUE TITLE
CD 구성

### ISSUE THREAD

**Issue by hellices** [shinhancard/dev-portal#66]
현재 레포에서는 github action으로 ecr에 이미지를 빌드하는것까지 구성하고 cd를 위한 별도 레포지토리를 만듦.
cd는 aws sandbox에 올려야하는데, 현재 레포가 깃허브 퍼블릭에 있다는 점을 고려하여 flux로 구성해본다

**Comment by hellices** [comment]
다음을 참고하여 구성을 진행함
https://fluxcd.io/flux/guides/image-update/

ecr에 등록된 이미지를 스캔하여 배포하는 방식이다.

flux container에서 ecr에 질의해야 하나 private registry로 인증 오류 발생함

**Comment by hellices** [comment]
https://fluxcd.io/flux/guides/cron-job-image-auth/#aws-elastic-container-registry

ecr credential은 정책 상 12시간마다 갱신된다.
flux는 k8s job으로 매6시간마다 토큰을 재발급해 secret으로 업데이트하는 전략을 가이드함.

현승님에 service account 발급 요청하여 진행중. sa에 할당된 권한 부족으로 추가 점검 예정

**Comment by hellices** [comment]
[dev-portal-flux-cd](https://github.com/shinhancard/dev-portal-flux-cd)

**Comment by hellices** [comment]
flux control plane을 모니터링하기 위해 다음을 진행 할 예정
https://fluxcd.io/flux/guides/monitoring/

**Comment by hellices** [comment]
grafana

https://swa-grafana.shrnd.link/d/flux-control-plane/flux-control-plane
https://swa-grafana.shrnd.link/d/flux-cluster/flux-cluster-stats

배포 성공 여부를 모니터링할 수 있음.

**Comment by seowjin1060** [comment]
![image](https://github.com/shinhancard/dev-portal/assets/26168539/bf705d2b-f8d4-4940-95b3-51e181f180d5)
'^main-[a-fA-F0-9]+-(?P<ts>.*)' 형식으로 CD 변경 완료. 배포된 pod가 없어 Flux 동작 확인중

**Comment by hellices** [comment]
1. github action을 통해서 ecr에 이미지 2차례 배포함.
![스크린샷 2023-08-03 오후 2 06 53](https://github.com/shinhancard/dev-portal/assets/5661904/f38efc81-384c-44db-9894-c5677eb136de)

2. 배포 결과 flux policy에서 감지함 확인(imagepolicy/backstage)
![스크린샷 2023-08-03 오후 2 07 52](https://github.com/shinhancard/dev-portal/assets/5661904/ba067920-a6be-47cc-8cf1-a6d75f36267c)

3. deploy에 최신 이미지로 변경됨 확인
![스크린샷 2023-08-03 오후 2 09 04](https://github.com/shinhancard/dev-portal/assets/5661904/93dea5ef-3e4b-47a4-b59d-6ef1ff919bfe)

---
# limitation
- github action 빌드에 대략 5분 소요
- flux ImagePolicy는 ecr에 업로드 된 이미지를 매 1분마다 조회하여 태그 확인
- flux ImageUpdateAutomation는 이미지가 업데이트된 것을 매 1분마다 체크하여 deployment에 반영

즉, 배포에 최대 10분정도의 delay가 생길 수 있음.

**Comment by hellices** [comment]
@shinhancard/dev_portal_team @YOOMYE89 리뷰 시 내용 공유 예정.

**Comment by hellices** [comment]
https://github.com/shinhancard/dev-portal/wiki/GitOps-%EC%A0%84%EB%9E%B5
