### ISSUE TITLE
feat: 개발 / 운영 빌드 환경 분리

### ISSUE THREAD

**Issue by seowjin1060** [shinhancard/dev-portal#69]
### Description

로컬 빌드시 app-config.yaml을,  EKS로 배포시 app-config.production.yaml을 참조해야함

- app 설정에 대해 sqlite. / postgres로 각각 분기된 파일이 기 작성된것으로 확인

- yarn build시 app-config.yaml을 기본적으로 참조함 
   운영에서는  app-config.production.yaml 참조 필요

**Comment by seowjin1060** [comment]
![image](https://github.com/shinhancard/dev-portal/assets/26168539/c267e47d-82fb-47af-bf5f-78c855005fff)
docker파일에 production으로 분기된것으로 확인되어 종료

**Comment by seowjin1060** [comment]
yarn build:all시 Backstage cli를 통해 전체 패키지를 빌드하는데, 
이 CLI에서 --config 옵션을 지원하지 않음 ;;;
https://github.com/backstage/backstage/issues/14329

backend build에서 --config 옵션으로 운영 config를 로딩하도록 해보겠음

**Comment by hellices** [comment]
Dockerfile에서 빌드전에 app.production.config.yaml을 app.config.yaml로 복사하면?

**Comment by seowjin1060** [comment]
> Dockerfile에서 빌드전에 app.production.config.yaml을 app.config.yaml로 복사하면?
로컬에서 docker build를 사용하지 않는 조건하에 동작할것 같습니다. 
우선 현재 버전은  아예 dockerfile에서 app.production.config.yaml을 로딩하도록 하였습니다 

`CMD ["node", "packages/backend", "--config", "app-config.production.yaml"]`
