### ISSUE TITLE
project initiailze

### ISSUE THREAD

**Issue by hellices** [shinhancard/dev-portal#7]
backstage import

**Comment by YOOMYE89** [comment]
pnpm 모노레포 구조로 변경 진행 중

**Comment by hellices** [comment]
Dependabot alerts 체크하면서 진행 필요

**Comment by wijihoon** [comment]
![image](https://github.com/hellices/dev-portal/assets/76634761/ef1f8f26-2122-4c94-a1bb-f93569ecffcf)

**Comment by YOOMYE89** [comment]
# 모노레포
참고 : [모던 프론트엔드 프로젝트 구성 기법 - 모노레포편] (https://d2.naver.com/helloworld/0923884) 

```
모노레포란 버전 관리 시스템에서 두 개 이상의 프로젝트 코드가 동일한 저장소에 저장되는 소프트웨어 개발 전략
```

![image](https://github.com/hellices/dev-portal/assets/59650687/d7e1a8ac-4b24-44d9-8107-10870eaa89d5)



## 관리 측면
 - 코드 공유: 서로 다른 프로젝트 간에 쉽게 소스 코드를 공유

 - 일관성 있는 도구: 서로 다른 프로젝트들(심지어 서로 다른 프레임워크를 사용하더라도)에서 일관된 개발 경험을 제공

 - 스케폴딩: 새로운 프로젝트를 생성할 때 초기 코드를 쉽게 생성

 - 프로젝트 제약 및 가시성(visibility): 저장소 내에서 의존 관계를 제한하는 규칙 정의 지원. 예를 들어, 일부 프로젝트를 팀 전용으로 표시하거나 특정 프레임워크을 사용 중임을 기술.

## 속도 측면
 - 로컬 캐싱: 같은 머신에서 같은 것을 두 번 빌드하거나 테스트하지 않음

 - 분산 캐싱: 다양한 환경에서 캐시 아티팩트를 공유. 즉, 조직 단위로 여러 CI 환경에 걸쳐 같은 것을 두 번 빌드, 테스트하지 않음

 - 로컬 작업 오케스트레이션: 빌드 및 테스트 등의 작업을 순서에 맞게 병렬로 실행

 - 분산 작업 실행: 단일 시스템에서 실행되어 여러 시스템에 명령을 전달

변화에 영향을 받는 프로젝트 감지: 변경의 영향을 받을 수 있는 항목을 결정하여 영향을 받는 프로젝트만 빌드/테스트

## 구조 파악 측면
 - 워크스페이스 분석: 추가 구성 없이 주어진 워크 스페이스의 의존성 관계를 분석

 - 의존성 그래프 시각화: 프로젝트 및 작업 간의 종속 관계를 시각화

**Comment by YOOMYE89** [comment]
# PNPM 구조로 바꾼 모습

<img width="845" alt="스크린샷 2023-07-06 오후 9 07 04" src="https://github.com/hellices/dev-portal/assets/59650687/173c8ab5-50a6-4995-a993-89eb3e0c125c">

## 인스톨은 가능하지만 실행 했을 경우
<img width="1131" alt="스크린샷 2023-07-06 오후 9 07 57" src="https://github.com/hellices/dev-portal/assets/59650687/be4433a7-cf50-4d25-915c-e7f41ae75f12">


- backstage-cli를 통해서 개발환경 실행하고 빌드 함
- cli 자체가 yarn을 통해서 만들어졌고, yarn 디펜던시가 있음. 
- lock파일을 본다는 것은 yarn install후에 만들어지는 node_module을 체크하거나, 내부에 바이너리를 추적하기 위함

```
결론 pnpm을 통한 모노레포로 가려면 cli를 뜯어내고 vite 나 webpack을 통해서 빌드해야함.
하지만 cli를 뜯어내면 번들링 되는 자원(js, css 등) Rule set 을 비롯해서 번들링 후 처리되는 Plugin까지 모두 찾아서 다시 만들어 줘야함
 --> 고통스러움.... 쉽게 가고싶음 yarn 패키지 관리 툴을 통한 모노레포 구조로 가는게 좋을 거 같음.. 
```

**Comment by YOOMYE89** [comment]
![image](https://github.com/hellices/dev-portal/assets/59650687/5a9e57a2-ad78-43ae-a58b-0e335fad1595)


```
나는 yarn을 느리고... 느리고... 느려서 싫어하기 때문에
더구나 나는 포기를 모르는 씹x끼? 이기 때문에 속도라도 빠르게 빌드 하고자 함
이에 turbo를 넣어서 번들링 환경을 구성하겠음.
```

# Turbo
[터보] https://www.npmjs.com/package/turbo

- 번들링 또는 실행에 대한 cache 처리가 가능한 번들링 미들웨어
- 속도가 빠름

**Comment by wijihoon** [comment]
#29 공동작업자 브랜치 전략

**Comment by wijihoon** [comment]
### backstage - storybook 적용

#### 분석
1. storybook pakage main.js
> backstage-core-stories 설정 ex) 스토리북에 사용될 컴퍼넌트 디렉토리
> webpack5 빌더를 통해 storybook 도구 addon
>> 우리는 웹팩 빌더가 아닌 터보를 사용할 듯 (변환 작업 필요)
> storybook 도구 정보는 (https://storybook.js.org/integrations) 확인 추후 유용한 도구 추가 확장 가능
> 이후 컴퍼넌트 디렉토리에 *.stories.tsx 찾아 module 추가

#### 개발
1. storybook pakage 적용 필요
2. 빌더 방식 수정 필요 (webpack -> turbopack)
 - webpack 대비 700배 빠른 업데이트 속도
 - webpack 대비 4배 빠른 콜드 스타트(초기 실행 속도)
 - Vite 대비 10배 빠른 업데이트 속도
3. backstage-core-stories 추가 (backstage 공식 깃허브 stories 참조)
4. concurrently 동시 실행 적용 (storybook 모노래포 활용 위함)

**Comment by wijihoon** [comment]
![image](https://github.com/hellices/dev-portal/assets/76634761/7f3677ad-2047-48fa-8b50-c9692ca5fc53)

https://velog.io/@wjs4199/React-npm-install%EC%8B%9C-node-gyp-%EC%97%90%EB%9F%AC

**Comment by wijihoon** [comment]
**feature/7** 브랜치 생성 및 storybook 1st install
---
backstage/storybook 참조하여 생성하였음
하지만, 해당 directory를 접근하는 scripts가 찾지를 못 하고 있음
좀 더 검토 후 작업 필요!!!
---

**Comment by wijihoon** [comment]
![image](https://github.com/hellices/dev-portal/assets/76634761/08593a2f-5bb7-404b-846d-66e7032f96b6)

**Comment by wijihoon** [comment]
**feature/7** backstage storybook 1rd rollback

```
롤백 이유...
1. root yarn dev 시 core-component 이슈 발생...
2. storybook은 정상 작동은 함

(주) core-component는 storybook 사용 시 필수 dependency임 고로 처음부터... 다시 시작
```

**Comment by wijihoon** [comment]
**feature/7** backstage storybook 4th commit


### 작업 내역
1. storybook 별도 패키지 생성 (별도 모듈 관리를 위해 한 패키지로 묶음 ex) pakages, plugins 등)
2. storybook 내 pakages, plugins 등 폴더 생성하여 core-component, home, org, search, stack-overflow등 생성
3. addon 추가 (단, 최신 7버전등 으로 업데이트 하였으나 오류로 인해 롤백하였음)


### 실행 방법
- dev-portal/storybook 이동 후 yarn install
- project root pakage.json 과 별개로 storybook 폴더 내 pakage.json 실행 (yarn start)

### 추후 개선 사항
- migration from webpack
- root pakage.json run 시 벙렬 실행 필요
- root yarn install 시 storybook 같이 설치 필요 (현재는 각 폴더로 이동하여 install 필요)

**Comment by YOOMYE89** [comment]
## 개선 및 작업 완료
 1. yarn dev 시에 스토리북 && 개발 서버 로드 완료
 2. addon관련 에러 확인 후 backstage 기본 addon setup 필요시 추가할 예정

**Comment by YOOMYE89** [comment]
구조 작업 완료 
 1. Stoybook에서 작업 후
 2. package 로 복사하여 작업함.

**Comment by YOOMYE89** [comment]
7/21 금요일에 리뷰하고 클로우즈 예정

**Comment by hellices** [comment]
#53 리뷰하기
discussion에 backstage cli에 있는 내용들 이해하기 https://github.com/hellices/dev-portal/discussions/54
