### ISSUE TITLE
feat: Plugin 예제 생성

### ISSUE THREAD

**Issue by YOOMYE89** [shinhancard/dev-portal#71]
Plugin 예제를 작성하여 넣고 Storybook에 넣어줌

**Comment by YOOMYE89** [comment]
Git lab - backstage 연동해서 작업하는 방향으로 진행한다.

**Comment by YOOMYE89** [comment]
스웨거 연동 하여 View로 가져오는 방법을 생각해보자

**Comment by wijihoon** [comment]
#63 Feature 해당 issue에서 진행 예정

**Comment by wijihoon** [comment]
기존 storybook은 root/plugins 내 디렉토리를 참조하였으나...

생각해보니 굳이 storybook을 root프로젝트와 연계할 필요가 있을가 고민하다가...

아에 별도의 component 관리만 할 수 있는 독립 환경으로 나눌 수 있을가 싶어 Storybook 공식 github에서 지원하는 design-system 프로젝트를 clone하여 적용시켜 보았는데 아주 잘 적용되며, 더 많은 template을 지원하여 

feature/71_template_add 브런치에 Push한 상태이다.

회의 시간에 논의하여 merge할 지 정해보자~

**Comment by wijihoon** [comment]
![image](https://github.com/shinhancard/dev-portal/assets/76634761/ffb1d3b1-158a-450f-b955-2657accd9a1d)

**Comment by YOOMYE89** [comment]
yarn new --select plugin

**Comment by hellices** [comment]
# 31 확인하고 진행해주세요...
swagger 통합 기능이 이미 있는듯

**Comment by hellices** [comment]
backstage plugin 개발 방법으로 진행
backstage api 기능으로 정리
